events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://site1:80;
        }

        location /second/ {
            proxy_pass http://site2:80;
        }
    }
}
